spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5000/elice
    username: elice
    password: Elice2team!@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Elice2team!@
    key-store-type: PKCS12
    key-alias: https_secret

  jwt:
    secret: BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234

file:
  upload-dir: ${HOME}/uploadBook
