spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  
  ssl:
    key-store:
    key-store-password:
    key-store-type:
    key-alias:

  jwt:
    secret: BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234BookStory1234

file:
  upload-dir: ${HOME}/uploadBook
